### ISSUE TITLE
Illegal callback invocation from native module

### ISSUE THREAD

**Issue by Sh3rawi** [sbugert/react-native-admob#110]
Hello,
After upgrading from 0.37 to 0.42, we're seeing this crash happen on android (I don't know about iOS as we haven't released it yet):
```
Fatal Exception: java.lang.RuntimeException: Illegal callback invocation from native module. This callback type only permits a single invocation from native code.
       at com.facebook.react.bridge.CallbackImpl.invoke(CallbackImpl.java:32)
       at com.sbugert.rnadmob.RNAdMobInterstitialAdModule$1$1.onAdFailedToLoad(RNAdMobInterstitialAdModule.java:63)
       at com.google.android.gms.internal.zzdz.onAdFailedToLoad(Unknown Source)
       at com.google.android.gms.internal.zzep$zza.onTransact(Unknown Source)
       at android.os.Binder.transact(Binder.java:387)
       at com.google.android.gms.ads.internal.client.z.a(:com.google.android.gms.DynamiteModulesA:124)
       at com.google.android.gms.ads.internal.a.a(:com.google.android.gms.DynamiteModulesA:872)
       at com.google.android.gms.ads.internal.a.b(:com.google.android.gms.DynamiteModulesA:424)
       at com.google.android.gms.ads.internal.c.b(:com.google.android.gms.DynamiteModulesA:164)
       at com.google.android.gms.ads.internal.m.run(:com.google.android.gms.DynamiteModulesA:150)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7229)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

On a side note: Why have a callback for the requestAd if all the lifecycle events are fired to JS when they happen?

**Comment by ThrowJojo** [comment]
Seeing the same issue here too on Android.

**Comment by avishayhajbi** [comment]
+1

**Comment by Nick-Patrick** [comment]
Was there any solution / update for this?

**Comment by ndbroadbent** [comment]
I'm also seeing this crash. It's a common thing with RN on Android, when a callback is invoked more than once. The callback needs to be replaced with an event that can be fired multiple times. My app is crashing quite frequently, so I'll try to work on a PR for this.

**Comment by koenpunt** [comment]
Is this still an actual problem? If so, let me know and I will reopen.

**Comment by SpringCT** [comment]
Yes, I am getting these crashes... I am using:
    "react-native": "^0.47.0",
    "react-native-admob": "^1.3.2",

**Comment by koenpunt** [comment]
I believe this is no longer an issue with the v2 version. You'll find installation instructions in the [README](https://github.com/sbugert/react-native-admob#readme)

**Comment by KamranKhankhail** [comment]
+1,

**Comment by KamranKhankhail** [comment]
"react-native": "0.49.3"
"react-native-admob": "^2.0.0-beta.3"

**Comment by koenpunt** [comment]
@KamranKhankhail please open a new issue, preferably with how you're implementing it
