### ISSUE TITLE
Getting strange Rewarded Video crash when receiving push notifications (when app is closed)

### ISSUE THREAD

**Issue by booboothefool** [sbugert/react-native-admob#112]
If my app is closed, and I get a push notification: 

I get "Unfortunately, App has stopped"

with this:
```
03-16 19:05:50.181 17356 17356 I Ads     : Starting ad request.
03-16 19:05:50.181 17356 17356 I Ads     : Use AdRequest.Builder.addTestDevice("my_test_device") to get test ads on this device.
03-16 19:05:50.191 17356 17356 D AndroidRuntime: Shutting down VM
03-16 19:05:50.191 17356 17356 E UncaughtException:
03-16 19:05:50.191 17356 17356 E UncaughtException: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.PackageManager android.content.Context.getPackageManager()' on a null object reference
03-16 19:05:50.191 17356 17356 E UncaughtException: 	at com.google.android.gms.common.zzg.isGooglePlayServicesAvailable(Unknown Source)
03-16 19:05:50.191 17356 17356 E UncaughtException: 	at com.google.android.gms.common.zze.isGooglePlayServicesAvailable(Unknown Source)
03-16 19:05:50.191 17356 17356 E UncaughtException: 	at com.google.android.gms.internal.zzqe.zzaf(Unknown Source)
03-16 19:05:50.191 17356 17356 E UncaughtException: 	at com.google.android.gms.internal.zzek.zza(Unknown Source)
03-16 19:05:50.191 17356 17356 E UncaughtException: 	at com.google.android.gms.internal.zzek.zza(Unknown Source)
03-16 19:05:50.191 17356 17356 E UncaughtException: 	at com.google.android.gms.internal.zzfh.getRewardedVideoAdInstance(Unknown Source)
03-16 19:05:50.191 17356 17356 E UncaughtException: 	at com.google.android.gms.ads.MobileAds.getRewardedVideoAdInstance(Unknown Source)
03-16 19:05:50.191 17356 17356 E UncaughtException: 	at com.sbugert.rnadmob.RNAdMobRewardedVideoAdModule$1.run(RNAdMobRewardedVideoAdModule.java:116)
03-16 19:05:50.191 17356 17356 E UncaughtException: 	at android.os.Handler.handleCallback(Handler.java:739)
03-16 19:05:50.191 17356 17356 E UncaughtException: 	at android.os.Handler.dispatchMessage(Handler.java:95)
03-16 19:05:50.191 17356 17356 E UncaughtException: 	at android.os.Looper.loop(Looper.java:158)
03-16 19:05:50.191 17356 17356 E UncaughtException: 	at android.app.ActivityThread.main(ActivityThread.java:7229)
03-16 19:05:50.191 17356 17356 E UncaughtException: 	at java.lang.reflect.Method.invoke(Native Method)
03-16 19:05:50.191 17356 17356 E UncaughtException: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
03-16 19:05:50.191 17356 17356 E UncaughtException: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by booboothefool** [comment]
So it was happening with AdRewardedInterstitial as well. 

Turns out what the error was complaining about was basically the app wasn't ready and loaded yet, so instead of keeping it in my index, I simply moved:

```
    AdMobInterstitial.setTestDeviceID('EMULATOR');
    AdMobInterstitial.setAdUnitID(Config.ADMOB_INTERSTITIAL_UNIT_ID);

    AdMobInterstitial.addEventListener('interstitialDidLoad', () => {
      log('interstitialDidLoad');
      // alert('interstitialDidLoad');
    });
    AdMobInterstitial.addEventListener('interstitialDidFailToLoad', (err) => {
      log('interstitialDidFailToLoad');
    });
    // AdMobInterstitial.addEventListener('interstitialDidOpen', () => log('interstitialDidOpen'));
    AdMobInterstitial.addEventListener('interstitialDidClose', () => {
      log('interstitialDidClose');
      // pre-load another one
      AdMobInterstitial.requestAd();
      SimpleStore.save('lastInterstitialTime', moment());
    });
    // AdMobInterstitial.addEventListener('interstitialWillLeaveApplication', () => log('interstitialWillLeaveApplication'));

    // pre-load the initial ad
    AdMobInterstitial.requestAd();
```

further into the initialization of the app (after the user was logged in). Works great now.
