### ISSUE TITLE
react native v0.25 BUILD FAILED

### ISSUE THREAD

**Issue by webyonet** [sbugert/react-native-admob#17]
:RNAdMob:preBuild UP-TO-DATE
:RNAdMob:preDebugBuild UP-TO-DATE
:RNAdMob:compileDebugNdk UP-TO-DATE
:RNAdMob:compileLint
:RNAdMob:copyDebugLint UP-TO-DATE
:RNAdMob:checkDebugManifest
:RNAdMob:preDebugAndroidTestBuild UP-TO-DATE
:RNAdMob:preDebugUnitTestBuild UP-TO-DATE
:RNAdMob:preReleaseBuild UP-TO-DATE
:RNAdMob:preReleaseUnitTestBuild UP-TO-DATE
:RNAdMob:prepareComAndroidSupportAppcompatV72301Library UP-TO-DATE
:RNAdMob:prepareComAndroidSupportRecyclerviewV72301Library UP-TO-DATE
:RNAdMob:prepareComAndroidSupportSupportV42301Library UP-TO-DATE
:RNAdMob:prepareComFacebookFrescoDrawee081Library UP-TO-DATE
:RNAdMob:prepareComFacebookFrescoFbcore081Library UP-TO-DATE
:RNAdMob:prepareComFacebookFrescoFresco081Library UP-TO-DATE
:RNAdMob:prepareComFacebookFrescoImagepipeline081Library UP-TO-DATE
:RNAdMob:prepareComFacebookFrescoImagepipelineOkhttp081Library UP-TO-DATE
:RNAdMob:prepareComFacebookReactReactNative0191Library UP-TO-DATE
:RNAdMob:prepareComGoogleAndroidGmsPlayServicesAds830Library UP-TO-DATE
:RNAdMob:prepareComGoogleAndroidGmsPlayServicesBasement830Library UP-TO-DATE
:RNAdMob:prepareOrgWebkitAndroidJscR174650Library UP-TO-DATE
:RNAdMob:prepareDebugDependencies
:RNAdMob:compileDebugAidl UP-TO-DATE
:RNAdMob:compileDebugRenderscript UP-TO-DATE
:RNAdMob:generateDebugBuildConfig UP-TO-DATE
:RNAdMob:generateDebugAssets UP-TO-DATE
:RNAdMob:mergeDebugAssets UP-TO-DATE
:RNAdMob:generateDebugResValues UP-TO-DATE
:RNAdMob:generateDebugResources UP-TO-DATE
:RNAdMob:mergeDebugResources UP-TO-DATE
:RNAdMob:processDebugManifest UP-TO-DATE
:RNAdMob:processDebugResources UP-TO-DATE
:RNAdMob:generateDebugSources UP-TO-DATE
:RNAdMob:compileDebugJavaWithJavac UP-TO-DATE
:RNAdMob:extractDebugAnnotations UP-TO-DATE
:RNAdMob:mergeDebugProguardFiles UP-TO-DATE
:RNAdMob:packageDebugRenderscript UP-TO-DATE
:RNAdMob:packageDebugResources UP-TO-DATE
:RNAdMob:processDebugJavaRes UP-TO-DATE
:RNAdMob:transformResourcesWithMergeJavaResForDebug UP-TO-DATE
:RNAdMob:transformClassesAndResourcesWithSyncLibJarsForDebug UP-TO-DATE
:RNAdMob:mergeDebugJniLibFolders UP-TO-DATE
:RNAdMob:transformNative_libsWithMergeJniLibsForDebug UP-TO-DATE
:RNAdMob:transformNative_libsWithSyncJniLibsForDebug UP-TO-DATE
:RNAdMob:bundleDebug UP-TO-DATE
:RNAdMob:compileDebugSources UP-TO-DATE
:RNAdMob:assembleDebug UP-TO-DATE
:RNAdMob:compileReleaseNdk UP-TO-DATE
:RNAdMob:copyReleaseLint UP-TO-DATE
:RNAdMob:checkReleaseManifest
:RNAdMob:prepareReleaseDependencies
:RNAdMob:compileReleaseAidl UP-TO-DATE
:RNAdMob:compileReleaseRenderscript UP-TO-DATE
:RNAdMob:generateReleaseBuildConfig UP-TO-DATE
:RNAdMob:generateReleaseAssets UP-TO-DATE
:RNAdMob:mergeReleaseAssets UP-TO-DATE
:RNAdMob:generateReleaseResValues UP-TO-DATE
:RNAdMob:generateReleaseResources UP-TO-DATE
:RNAdMob:mergeReleaseResources UP-TO-DATE
:RNAdMob:processReleaseManifest UP-TO-DATE
:RNAdMob:processReleaseResources UP-TO-DATE
:RNAdMob:generateReleaseSources UP-TO-DATE
:RNAdMob:compileReleaseJavaWithJavac UP-TO-DATE
:RNAdMob:extractReleaseAnnotations UP-TO-DATE
:RNAdMob:mergeReleaseProguardFiles UP-TO-DATE
:RNAdMob:packageReleaseRenderscript UP-TO-DATE
:RNAdMob:packageReleaseResources UP-TO-DATE
:RNAdMob:processReleaseJavaRes UP-TO-DATE
:RNAdMob:transformResourcesWithMergeJavaResForRelease UP-TO-DATE
:RNAdMob:transformClassesAndResourcesWithSyncLibJarsForRelease UP-TO-DATE
:RNAdMob:mergeReleaseJniLibFolders UP-TO-DATE
:RNAdMob:transformNative_libsWithMergeJniLibsForRelease UP-TO-DATE
:RNAdMob:transformNative_libsWithSyncJniLibsForRelease UP-TO-DATE
:RNAdMob:bundleRelease UP-TO-DATE
:RNAdMob:compileReleaseSources UP-TO-DATE
:RNAdMob:assembleRelease UP-TO-DATE
:RNAdMob:assemble UP-TO-DATE
:RNAdMob:lint
Wrote HTML report to file:///Volumes/BackUp/Github/populerMatch/node_modules/react-native-admob/android/build/outputs/lint-results.html
Wrote XML report to file:///Volumes/BackUp/Github/populerMatch/node_modules/react-native-admob/android/build/outputs/lint-results.xml
Lint found 1 errors and 4 warnings
:RNAdMob:lint FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':RNAdMob:lint'.
> Lint found errors in the project; aborting build.
  
  Fix the issues identified by lint, or add the following to your build script to proceed with errors:
  ...
  android {
      lintOptions {
          abortOnError false
      }
  }
  ...

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':RNAdMob:lint'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:310)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:23)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:88)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
	at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:149)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:90)
	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:49)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
	at org.gradle.util.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(DaemonHealthTracker.java:47)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:66)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:71)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(HintGCAfterBuild.java:41)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:246)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: org.gradle.api.GradleException: Lint found errors in the project; aborting build.

Fix the issues identified by lint, or add the following to your build script to proceed with errors:
...
android {
    lintOptions {
        abortOnError false
    }
}
...
	at com.android.build.gradle.tasks.Lint.abort(Lint.groovy:164)
	at com.android.build.gradle.tasks.Lint.runLint(Lint.groovy:202)
	at com.android.build.gradle.tasks.Lint.this$6$runLint(Lint.groovy)
	at com.android.build.gradle.tasks.Lint$this$6$runLint$4.callCurrent(Unknown Source)
	at com.android.build.gradle.tasks.Lint.lintSingleVariant(Lint.groovy:171)
	at com.android.build.gradle.tasks.Lint$lintSingleVariant$3.callCurrent(Unknown Source)
	at com.android.build.gradle.tasks.Lint.lint(Lint.groovy:73)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:226)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:219)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:208)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:589)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:572)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 57 more

<img width="859" alt="screen shot 2016-05-12 at 21 00 17" src="https://cloud.githubusercontent.com/assets/973302/15224949/a6c915dc-1884-11e6-8114-e540bfa9e8f2.png">

**Comment by webyonet** [comment]
ok. this issue is closed with #16
sorry.
