### ISSUE TITLE
Error with RN 0.27 on interstitial 

### ISSUE THREAD

**Issue by eranbes** [sbugert/react-native-admob#31]
Fatal Exception: com.facebook.react.bridge.NativeArgumentsParseException: TypeError: expected dynamic type `double', but had type `string' (constructing arguments for RNAdMobInterstitial.showAd at argument index 0)
       at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:310)
       at com.facebook.react.bridge.NativeModuleRegistry$ModuleDefinition.call(NativeModuleRegistry.java:187)
       at com.facebook.react.bridge.NativeModuleRegistry.call(NativeModuleRegistry.java:62)
       at com.facebook.react.bridge.CatalystInstanceImpl$NativeModulesReactCallback.call(CatalystInstanceImpl.java:420)
       at com.facebook.react.bridge.queue.NativeRunnableDeprecated.run(NativeRunnableDeprecated.java)
       at android.os.Handler.handleCallback(Handler.java:808)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
       at android.os.Looper.loop(Looper.java:193)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:197)
       at java.lang.Thread.run(Thread.java:848)
Caused by com.facebook.react.bridge.UnexpectedNativeTypeException: TypeError: expected dynamic type `double', but had type `string'
       at com.facebook.react.bridge.ReadableNativeArray.getDouble(ReadableNativeArray.java)
       at com.facebook.react.bridge.BaseJavaModule$8.extractArgument(BaseJavaModule.java:137)
       at com.facebook.react.bridge.BaseJavaModule$8.extractArgument(BaseJavaModule.java:130)
       at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:305)
       at com.facebook.react.bridge.NativeModuleRegistry$ModuleDefinition.call(NativeModuleRegistry.java:187)
       at com.facebook.react.bridge.NativeModuleRegistry.call(NativeModuleRegistry.java:62)
       at com.facebook.react.bridge.CatalystInstanceImpl$NativeModulesReactCallback.call(CatalystInstanceImpl.java:420)
       at com.facebook.react.bridge.queue.NativeRunnableDeprecated.run(NativeRunnableDeprecated.java)
       at android.os.Handler.handleCallback(Handler.java:808)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)

**Comment by sbugert** [comment]
Can you show me the code where you call showAd?

**Comment by eranbes** [comment]
Sorry of course:
import {AdMobInterstitial} from 'react-native-admob';
AdMobInterstitial.requestAd(AdMobInterstitial.showAd);

Please note that it does not always happen (that error that is)

**Comment by sbugert** [comment]
Sorry, I forgot to answer!

I have not been able to reproduce the bug yet. Do you have any new information on the issue?

**Comment by eranbes** [comment]
Its all good you just need to update the documentation to reflect the code.
I now use it like:

`AdMobInterstitial.requestAd(err => /*ignore_the(err) && */ AdMobInterstitial.showAd()); `
instead of `AdMobInterstitial.requestAd(AdMobInterstitial.showAd);`

**Comment by grohsfabian** [comment]
Happening to me, can't really fix this. Someone ?

**Comment by ricardofavero** [comment]
I was getting this error because my ads had recently been created in AdMob. In this case, just wait a few minutes or hours and they will start to appear normally.
Another possibility is that you're providing a wrong unitID.

**Comment by Kris4an7** [comment]
Same problem. When I tried the solution above, the app doesn't get an error but the Interstitial never actually shows.
