### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/ads/InterstitialAd;

### ISSUE THREAD

**Issue by IacoCesar** [sbugert/react-native-admob#451]
After AndroidX migration received this error

RN 0.59.2

`java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/ads/InterstitialAd;
        at com.sbugert.rnadmob.RNAdMobInterstitialAdModule.<init>(RNAdMobInterstitialAdModule.java:48)
        at com.sbugert.rnadmob.RNAdMobPackage.createNativeModules(RNAdMobPackage.java:18)
        at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:42)
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:41)
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1212)
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1182)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1120)
        at com.facebook.react.ReactInstanceManager.access$900(ReactInstanceManager.java:123)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:943)
        at java.lang.Thread.run(Thread.java:761)`

**Comment by IacoCesar** [comment]
[#448 ](https://github.com/sbugert/react-native-admob/issues/448#issuecomment-504807659)
