### ISSUE TITLE
Execution failed for task ':app:processDebugResources'.

### ISSUE THREAD

**Issue by butavpaul** [sbugert/react-native-admob#548]
Hi. When I'm trying to launch the app on my device or to build the apk I get this error. If I remove the package the app it's working.
How can I solve this? Thank you!

`What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     C:\Users\Paul\.gradle\caches\transforms-2\files-2.1\65a7585b9bb154c619c54e8c3c28e865\play-services-ads-lite-19.6.0\AndroidManifest.xml:27:5-38:15: AAPT: error: unexpected element <queries> found in <manifest>.`

**Comment by Younanator** [comment]
Getting the same issue

**Comment by ahmad923245** [comment]
i m aslo geeting this issue

**Comment by minhasmaqsood** [comment]
I am also getting this issue

**Comment by ahmad923245** [comment]
@butavpaul find any solution?

**Comment by yunusaslancan** [comment]
@butavpaul find any solution?

**Comment by ananditasharma2120** [comment]
Change your gradle version in build.gradle as per the series version you are using.These are the updated versions.
3.3.3
3.4.3
3.5.4
3.6.4
4.0.1

**Comment by wandersonalwes** [comment]
1. Open your project's `android` folder in Android Studio, and wait a moment, a notification will appear in the bottom right corner asking for Gradle to be updated. You must click on update, wait for the update...

2. After finishing the Gradle update run `./gradlew clean` in the android folder.

3. Open your complete project and run `yarn android` or `npm run android` again.

Good luck 🎉

**Comment by ahmad923245** [comment]
> 1. Open your project's `android` folder in Android Studio, and wait a moment, a notification will appear in the bottom right corner asking for Gradle to be updated. You must click on update, wait for the update...
> 2. After finishing the Gradle update run `./gradlew clean` in the android folder.
> 3. Open your complete project and run `yarn android` or `npm run android` again.
> 
> Good luck 🎉

android not open project properly

**Comment by diegocharles** [comment]
> 1. Open your project's `android` folder in Android Studio, and wait a moment, a notification will appear in the bottom right corner asking for Gradle to be updated. You must click on update, wait for the update...
> 2. After finishing the Gradle update run `./gradlew clean` in the android folder.
> 3. Open your complete project and run `yarn android` or `npm run android` again.
> 
> Good luck 🎉

@wandersonalwes I don't know you but I own you a coffee haha. Thank you!

**Comment by viren-joshi** [comment]
> 1. Open your project's `android` folder in Android Studio, and wait a moment, a notification will appear in the bottom right corner asking for Gradle to be updated. You must click on update, wait for the update...
> 2. After finishing the Gradle update run `./gradlew clean` in the android folder.
> 3. Open your complete project and run `yarn android` or `npm run android` again.
> 
> Good luck 🎉

how do I fix this, if i'm using VS Code, could you please help?

**Comment by fdmxfarhan** [comment]
I owe you a coffee too. thanks!!

**Comment by CThu01** [comment]
Please answer for this solution

**Comment by RuslanAltymyshev** [comment]
> 1. Open your project's `android` folder in Android Studio, and wait a moment, a notification will appear in the bottom right corner asking for Gradle to be updated. You must click on update, wait for the update...
> 2. After finishing the Gradle update run `./gradlew clean` in the android folder.
> 3. Open your complete project and run `yarn android` or `npm run android` again.
> 
> Good luck 🎉

thank you @wandersonalwes

**Comment by nisith44** [comment]
* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Could not resolve all files for configuration ':app:debugCompileClasspath'.
   > Could not resolve com.android.support:appcompat-v7:25.+.
     Required by:
         project :app
      > Failed to list versions for com.android.support:appcompat-v7.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/android/support/appcompat-v7/maven-metadata.xml.


Steps
=====
first try this--->
it can be connection err to maven repositary server.. so try again some times..

if not work then
----------------

Goto Android studio SDK manager-->SDK tool-->show package details-->select 30.0.0
Goto Android studio SDK manager-->SDK Platforms-->select 32

then try to build --> ionic cordova build android

if key board err came use this command--> ionic cordova plugin rm ionic-plugin-keyboard


if build unsuccess
===================
ionic cordova platform rm android
ionic cordova platform add android@9.1.0
ionic cordova build android

**Comment by mamonaabdullah122** [comment]
I have this issue help

> Configure project :react-native-reanimated
AAR for react-native-reanimated has been found
/Volumes/Os/FirebaseAuth/node_modules/react-native-reanimated/android/react-native-reanimated-69-jsc.aar

> Task :app:processDebugResources FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings
178 actionable tasks: 2 executed, 176 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > Android resource linking failed
     ERROR:/Volumes/Os/FirebaseAuth/android/app/src/main/res/drawable/launch_screen.xml:6: AAPT: error: resource drawable/background_splash (aka com.firebaseauth:drawable/background_splash) not found.
         

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > Android resource linking failed
     ERROR:/Volumes/Os/FirebaseAuth/android/app/src/main/res/drawable/launch_screen.xml:6: AAPT: error: resource drawable/background_splash (aka com.firebaseauth:drawable/background_splash) not found.
         

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s

    at makeError (/Volumes/Os/FirebaseAuth/node_modules/execa/index.js:174:9)
    at /Volumes/Os/FirebaseAuth/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (/Volumes/Os/FirebaseAuth/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:109:5)
    at async Command.handleAction (/Volumes/Os/FirebaseAuth/node_modules/@react-native-community/cli/build/index.js:192:9)
info Run CLI with --verbose flag for more details.

**Comment by maheshboppo** [comment]
> 1. Open your project's `android` folder in Android Studio, and wait a moment, a notification will appear in the bottom right corner asking for Gradle to be updated. You must click on update, wait for the update...
> 2. After finishing the Gradle update run `./gradlew clean` in the android folder.
> 3. Open your complete project and run `yarn android` or `npm run android` again.
> 
> Good luck 🎉


I tried this but still getting the same error !

**Comment by syedrahaman92** [comment]
> > 1. Open your project's `android` folder in Android Studio, and wait a moment, a notification will appear in the bottom right corner asking for Gradle to be updated. You must click on update, wait for the update...
> > 2. After finishing the Gradle update run `./gradlew clean` in the android folder.
> > 3. Open your complete project and run `yarn android` or `npm run android` again.
> > 
> > Good luck 🎉
> 
> I tried this but still getting the same error !

Make sure your Internet connection is not restricted. Try using VPN. I hope it helps
