### ISSUE TITLE
Installing failed to link

### ISSUE THREAD

**Issue by naji247** [sbugert/react-native-admob#9]
Hey guys I'm having trouble installing this package. Maybe I am doing something wrong?

I ran ```npm i react-native-admob -S```

then downloaded the framwork and imported it.
<img width="606" alt="screen shot 2016-03-20 at 2 00 52 pm" src="https://cloud.githubusercontent.com/assets/1920483/13907113/366ed57e-eea4-11e5-813e-e0284f89d6f3.png">

then installed rnpm globally, ran  ```npm install react-native-admob --save```, and then tried to ```rnpm link```

<img width="1440" alt="screen shot 2016-03-20 at 1 59 24 pm" src="https://cloud.githubusercontent.com/assets/1920483/13907126/78e8fd9e-eea4-11e5-85f4-8e48664382b6.png">

Text version of trace
```shell
rnpm-link info Linking react-native-admob android dependency
/Users/naseem.alnaji/.nvm/versions/node/v5.8.0/lib/node_modules/rnpm/node_modules/semver/semver.js:293
    throw new TypeError('Invalid Version: ' + version);
    ^

TypeError: Invalid Version: 0.22.04
    at new SemVer (/Users/naseem.alnaji/.nvm/versions/node/v5.8.0/lib/node_modules/rnpm/node_modules/semver/semver.js:293:11)
    at compare (/Users/naseem.alnaji/.nvm/versions/node/v5.8.0/lib/node_modules/rnpm/node_modules/semver/semver.js:566:10)
    at Function.lt (/Users/naseem.alnaji/.nvm/versions/node/v5.8.0/lib/node_modules/rnpm/node_modules/semver/semver.js:600:10)
    at /Users/naseem.alnaji/.nvm/versions/node/v5.8.0/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/src/android/getPrefix.js:10:16
    at Array.forEach (native)
    at getPrefix (/Users/naseem.alnaji/.nvm/versions/node/v5.8.0/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/src/android/getPrefix.js:8:12)
    at registerNativeAndroidModule (/Users/naseem.alnaji/.nvm/versions/node/v5.8.0/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/src/android/registerNativeModule.js:8:18)
    at /Users/naseem.alnaji/.nvm/versions/node/v5.8.0/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/src/link.js:28:28
    at fn (/Users/naseem.alnaji/.nvm/versions/node/v5.8.0/lib/node_modules/rnpm/node_modules/async/lib/async.js:746:34)
    at /Users/naseem.alnaji/.nvm/versions/node/v5.8.0/lib/node_modules/rnpm/node_modules/async/lib/async.js:1213:16
```

**Comment by naji247** [comment]
Error was fixed by repeating with npm 2.14
